const owner="domingosferrazfonseca283-blip",repo="Hhjjh",branch="livro-python";
const api=`https://api.github.com/repos/${owner}/${repo}/contents/LIVRO_PYTHON`;
const rawBase=`https://raw.githubusercontent.com/${owner}/${repo}/${branch}/`;
const volumes=[
["01_INICIO_ABSOLUTO","Volume 1 — Início absoluto"],["02_FUNDAMENTOS","Volume 2 — Fundamentos"],["03_LOGICA_E_DADOS","Volume 3 — Lógica e estruturas de dados"],["04_FUNCOES","Volume 4 — Funções"],["05_POO","Volume 5 — Programação orientada a objetos"],["06_MODULOS_FICHEIROS","Volume 6 — Módulos e ficheiros"],["07_APIS_BANCOS_DADOS","Volume 7 — APIs e bases de dados"],["08_TESTES_DEBUG","Volume 8 — Testes, debugging e qualidade"],["09_PYTHON_AVANCADO","Volume 9 — Python avançado"],["10_PYTHON_PROFISSIONAL","Volume 10 — Python profissional"],["11_PROJETOS_PROFISSIONAIS","Volume 11 — Projetos profissionais"],["12_PROJETOS_AVANCADOS","Volume 12 — Projetos avançados"],["13_ENGENHARIA_SOFTWARE","Volume 13 — Engenharia de software"],["14_DADOS_AUTOMACAO_IA","Volume 14 — Dados, automação e IA"],["15_DESENVOLVIMENTO_WEB","Volume 15 — Desenvolvimento web"],["16_MACHINE_LEARNING","Volume 16 — Machine Learning"],["17_DEEP_LEARNING","Volume 17 — Deep Learning"]];
const nav=document.querySelector("#volumes"), reader=document.querySelector("#reader"), status=document.querySelector("#status"), search=document.querySelector("#search");
let lessons=[];
function esc(s){return s.replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));}
function md(s,dir){let x=esc(s);x=x.replace(/^###### (.*)$/gm,"<h6>$1</h6>").replace(/^##### (.*)$/gm,"<h5>$1</h5>").replace(/^#### (.*)$/gm,"<h4>$1</h4>").replace(/^### (.*)$/gm,"<h3>$1</h3>").replace(/^## (.*)$/gm,"<h2>$1</h2>").replace(/^# (.*)$/gm,"<h1>$1</h1>").replace(/\*\*(.*?)\*\*/g,"<strong>$1</strong>").replace(/\*(.*?)\*/g,"<em>$1</em>").replace(/!\[([^\]]*)\]\(([^)]+)\)/g,(m,a,b)=>`<img alt="${a}" src="${b.startsWith("http")?b:rawBase+"LIVRO_PYTHON/"+dir+"/"+b.replace(/^\.\.\//,"")}">`).replace(/\[([^\]]+)\]\(([^)]+)\)/g,'<a href="$2">$1</a>').replace(/^    (.*)$/gm,"<pre>$1</pre>").replace(/^(?!<h|<pre|<img|<a|<ul|<ol|<li|$)(.+)$/gm,"<p>$1</p>");return x;}
async function loadVolume(dir,title,details){try{const r=await fetch(api+"/"+dir);const data=await r.json();const files=data.filter(x=>x.type==="file"&&x.name.endsWith(".md"));files.sort((a,b)=>a.name.localeCompare(b.name,navigator.language,{numeric:true}));const box=document.createElement("details");box.open=details;const sum=document.createElement("summary");sum.textContent=title;box.append(sum);files.forEach(f=>{const b=document.createElement("button");b.className="lesson";b.textContent=f.name.replace(".md","").replace(/^\d+_/,"").replaceAll("_"," ");b.dataset.name=f.name.toLowerCase();b.onclick=()=>openLesson(dir,f.name,b);box.append(b);lessons.push({b,title,dir,file:f.name});});nav.append(box);}catch(e){console.error(e);}}
async function openLesson(dir,file,btn){document.querySelectorAll(".lesson").forEach(x=>x.classList.remove("active"));btn.classList.add("active");reader.innerHTML="<p>⏳ A carregar aula...</p>";try{const r=await fetch(rawBase+"LIVRO_PYTHON/"+dir+"/"+file);const text=await r.text();reader.innerHTML=md(text,dir);}catch(e){reader.innerHTML="<h2>Não foi possível carregar a aula.</h2><p>Verifique a ligação à internet.</p>";}}
async function start(){for(let i=0;i<volumes.length;i++)await loadVolume(volumes[i][0],volumes[i][1],i===0);status.textContent="17 volumes carregados";}search.oninput=()=>{const q=search.value.toLowerCase();lessons.forEach(x=>x.b.hidden=q&&!x.b.dataset.name.includes(q));};start();
if("serviceWorker" in navigator) navigator.serviceWorker.register("sw.js");
let deferred;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferred=e;document.querySelector("#install").hidden=false;});document.querySelector("#install").onclick=async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null;}};
