plugins { id 'com.android.application' }

android {
    namespace 'com.domingosferrazfonseca.livropython'
    compileSdk 35

    defaultConfig {
        applicationId 'com.domingosferrazfonseca.livropython'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName '1.1'
    }
}

tasks.register('copyBook', Copy) {
    from(rootProject.file('../LIVRO_PYTHON'))
    into(layout.projectDirectory.dir('src/main/assets/LIVRO_PYTHON'))
    include('**/*.md')
    include('**/*.svg')
}

preBuild.dependsOn(copyBook)

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.webkit:webkit:1.12.1'
}
